export { default as OrderTable } from "./OrderTable";
export { default as ClienteForm } from "./CustomerForm";
export { default as OrderDetailsForm } from "./OrderDetailsForm";
export { default as PrendasForm } from "./PrendasForm";
export { default as PaymentForm } from "./PaymentForm";
export { default as DeleteOrderDialog } from "./DeleteOrderDialog";
export { default as DeletePaymentButton } from "./DeletePaymentButton";
export { default as OrderCustomerSection } from "./OrderCustomerSection";
export { default as ReceiptDownloadButton } from "./ReceiptDownloadButton";
export { default as OrderSection } from "./OrderSection"
export { default as OrderPaymentSection } from "./OrderPaymentSection"
export { default as EditOrderItemsDialog } from "./EditOrderItemsDialog";